import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col h-screen ${inter.className}`}>
        <div className="flex-1">
          {children}
        </div>
        <footer className="bg-black text-white text-center py-4">Footer</footer>
      </body>
    </html>
  );
}
